dataset:
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: DummyEdge
  format: PyG-HeterophilousGraphDataset
  name: Questions
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: RWSE
  split_mode: random
  split: [0.6, 0.2, 0.2]
  task: node
  task_type: classification
  transductive: true
gnn:
  act: gelu
  agg: mean
  batchnorm: true
  dim_inner: 96
  dropout: 0.2
  head: node
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
graphormer:
  use_graph_token: false
gt:
  attn_dropout: 0.5
  batch_norm: false
  dim_hidden: 96
  dropout: 0.2
  layer_norm: false
  layer_type: GCN+Transformer
  layers: 3
  n_heads: 4
metric_best: accuracy
model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GPSModel
optim:
  base_lr: 0.0005
  clip_grad_norm: true
  max_epoch: 200
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1e-5
out_dir: results
posenc_GraphormerBias:
  enable: false
  node_degrees_only: true
  num_in_degrees: 729
  num_out_degrees: 89
  num_spatial_types: 20
posenc_LapPE:
  dim_pe: 4
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 4
  enable: false
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 16
  enable: true
  kernel:
    times_func: range(1,17)
  model: Linear
  raw_norm_type: BatchNorm
train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  sampler: full_batch
wandb:
  project: questions
  use: false
